### ISSUE TITLE
Check the kubernetes printers

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#12]
we should be consistent with Kubernetes

it is wroth checking if we can re-use the Kubernetes kubectl printers from:

https://github.com/kubernetes/kubernetes/tree/master/pkg/printers

Otherwise https://github.com/gosuri/uitable might be handy as well

**Comment by tzununbekov** [comment]
Checked kubernetes printers - they looks powerful but adding them to print simple tables for me seems like overkill, especially considering the time that it may take to integrate it with our code

Added uitable to print tables, but will keep in mind k8s printers if we need advanced printing library
