### ISSUE TITLE
Consider using go modules instead of `dep`

### ISSUE THREAD

**Issue by grzesiek** [triggermesh/tm#123]
## Description

We currently use both `dep` and go modules in this project.

After the release of v0.0.11 these dependencies are out of sync. 

Is there a way to ensure that `go.mod` and `go.sum` get updated before releasing a new version of the `tm`?

/cc @tzununbekov @sebgoa

**Comment by tzununbekov** [comment]
@grzesiek I agree, we should get rid of `dep` in favor of go modules. I'll take a look at this after my current task

**Comment by grzesiek** [comment]
@tzununbekov Can I also recommend using semantic versioning? We already do have major, minor and patch version like `vMAJOR.MINOR.PATCH`, but it appears that we bumped the patch version even after introducing a new functionality (like using Knative 0.6 now depends on tm tool `v0.0.11` and we also bundled `tektoncd` packages). I think we probably should bump minor version and release `v0.1.0`) as per [SemVer](https://semver.org/):

> Given a version number MAJOR.MINOR.PATCH, increment the:
> MINOR version when you add functionality in a backwards-compatible manner, and

**Comment by sebgoa** [comment]
not so fast I think, I am hearing about issues with go modules.

I think we should wait a bit and let the dust settle on go modules.

**Comment by grzesiek** [comment]
@sebgoa Can you share what you've heard is wrong with `go modules`?

**Comment by sebgoa** [comment]
Nothing personally, just slack and twitter comments that make me want to be careful.

Things like this:
https://www.reddit.com/r/golang/comments/avowe9/go_modules_seem_very_broken/

**Comment by grzesiek** [comment]
I think that in version 1.12 a lot of problems have been resolved. At GitLab, we are using go modules successfully since 1.12, and although this entire ecosystem is not perfect yet, for me, personally, go modules work quite well. I do agree that for the time being `tm` might want to maintain both, go mods and `dep`, but eventually Knative will - probably - migrate.

**Comment by tzununbekov** [comment]
Last few versions of go modules worked pretty well for us, so we use them as preferable dependency management method now:  
https://github.com/triggermesh/tm/releases/tag/v0.1.0
