### ISSUE TITLE
make the cmd go gettable

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#14]
we should be able to install the command with a simple go get like

```
go get github.com/triggermesh/tm/cmd/tm
```

the `cmd` directory may need to be refactored and the `main.go` re-written

**Comment by tzununbekov** [comment]
@sebgoa right now I can install tm with the following command:
```
go get github.com/triggermesh/tm
```
Isn't this ok?

**Comment by sebgoa** [comment]
yes that's fine.
