### ISSUE TITLE
Deploy should not create a new service

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#141]
When we create multiple times we actually create a new service and we do not do an update.

We should find a way to do an `apply` to the service definition so that we get a new revision and can rollback.

**Comment by tzununbekov** [comment]
Not sure if I get it right, but we're updating service if the one with the same name already exist:
https://github.com/triggermesh/tm/blob/master/pkg/resources/service/create.go#L160-L180

If it doesn't work or it should work differently, please let me know in detail
