### ISSUE TITLE
Add Description for Push Command

### ISSUE THREAD

**Issue by danielhelfand** [triggermesh/tm#151]
`tm push` is the only command missing a description:

```
Triggermesh CLI

Usage:
  tm [command]

Available Commands:
  delete      Delete knative resource
  deploy      Deploy knative resource
  generate    Generate sample project
  get         Retrieve resources from k8s cluster
  help        Help about any command
  push        
  set         Set resource parameters
  version     Print the version number of tm CLI

Flags:
      --config string          k8s config file
  -d, --debug                  Enable debug output
      --dry                    Do not create k8s objects, just print its structure
  -h, --help                   help for tm
  -n, --namespace string       User namespace
  -o, --output string          Output format
      --registry-host string   Docker registry host address (default "knative.registry.svc.cluster.local")
      --wait                   Wait for the operation to complete

Use "tm [command] --help" for more information about a command.
```

Adding `Short: tm push description` [here](https://github.com/triggermesh/tm/blob/e5597a4fd68c3c4e39036ce4ffba8d9246982e2a/cmd/push.go#L27) would be nice to have.

**Comment by tzununbekov** [comment]
Hi @danielhelfand, thanks for reporting this issue
We replaced our custom components with tekton triggers in `tm push` internals recently and it still was in sort of testing mode. In my opinion, although `tm push` command based on tekton triggers seems to be a better option, old push command provides better user experience with less number of "moving" parts:
 - deploying pipeline based on tekton triggers, [readme](https://github.com/triggermesh/tm/blob/a7f5923742f3a0464e7c9ad3e67fb13642369954/README.md#deployment-pipelines)
 - deploying pipeline based on triggermesh transceiver, [readme](https://github.com/triggermesh/tm/blob/c7373d8f45d35319f1134ce00c1126215aecd14d/README.md#deployment-pipelines)

We'll figure out which implementation is more suitable for us and merge it into upstream

**Comment by danielhelfand** [comment]
@tzununbekov Thanks for the detailed breakdown. Will keep an eye out for the updates, and look forward to seeing which approach makes it upstream.

**Comment by tzununbekov** [comment]
So, the transceiver branch has been merged into the upstream, documentation updated
Closing issue, @danielhelfand feel free to reopen it if you have any additional questions
