### ISSUE TITLE
Dockerfile is specific to cloudbuild setup

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#165]
Dockerfile is written with the path of the go build image used in cloudbuild

Which means that you cannot build the image locally.

**Comment by sameersbn** [comment]
I see two options:

Options 1: Rename current `Dockerfile` to `Dockerfile.cloudbuild` and add a `Dockerfile` that uses multistage docker build to compile `tm` and build the image. `Dockerfile.cloudbuild` would be used in `cloudbuild.yaml` steps as it's currently configured.

Option 2: Use a single multistage Dockerfile to compile `tm` and build the image. Cloudbuild step to build `tm` can then be removed. Cloudbuild.yaml will only build the image and tag it appropriately.

**Comment by sebgoa** [comment]
I would do Option 1. 

note that we need an OSX binary in the release
