### ISSUE TITLE
Check that `go get github.com/triggermesh/tm` works

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/tm#190]
user reported that he had a build errors when run `go get github.com/triggermesh/tm ` command:   

```
# github.com/knative/pkg/kmeta
go/pkg/mod/github.com/knative/pkg@v0.0.0-20190624141606-d82505e6c5b4/kmeta/accessor.go:66:21: undefined: v1.Initializers
go/pkg/mod/github.com/knative/pkg@v0.0.0-20190624141606-d82505e6c5b4/kmeta/accessor.go:67:32: undefined: v1.Initializers
# github.com/tektoncd/triggers/pkg/client/clientset/versioned/typed/triggers/v1alpha1
go/pkg/mod/github.com/tektoncd/triggers@v0.1.0/pkg/client/clientset/versioned/typed/triggers/v1alpha1/triggers_client.go:84:32: undefined: serializer.DirectCodecFactory
# knative.dev/eventing/pkg/apis/duck/v1alpha1
go/pkg/mod/knative.dev/eventing@v0.12.0/pkg/apis/duck/v1alpha1/channelable_types.go:98:4: cannot use &"k8s.io/api/core/v1".ObjectReference literal (type *"k8s.io/api/core/v1".ObjectReference) as type *"knative.dev/pkg/apis/duck/v1".KReference in field value
```

**Comment by eddiewang** [comment]
can confirm that I got the same error. ended up using the release build.

**Comment by hechth** [comment]
Encountered the same problem, so seems to be still existing.

**Comment by tzununbekov** [comment]
thanks for confirming. This issue is caused by mixing different versions of the same packages to support backward compatibility with old build approaches. We're working on getting rid of these dependencies but it takes a bit more than we expected so for now there are two alternatives to `go get`:

- get binaries from the [latest](https://github.com/triggermesh/tm/releases/latest) release - we're keeping it in sync with the upstream
- `git clone`, `go install` - if you want to have your version of tm CLI installed

**Comment by tzununbekov** [comment]
Outdated dependencies and mixed versions are not the reason for a failing `go get` - in [this](https://github.com/triggermesh/tm/pull/197) PR we got rid of old components and it didn't help.
What actually caused the described issue is `go get` behavior:

> replace directives have no effect outside of your own module, so if you invoke go get outside of your own module, they have no effect.

https://github.com/golang/go/issues/30354

In other words, it means that dependency replacements that we have in go.mod are not honored if you run `go get github.com/triggermesh/tm` outside the module root path. We've updated the [readme](https://github.com/triggermesh/tm/blob/92b97dafb2ac9a96573a32da7633c45bebad01b0/README.md#installation) to avoid this issue. Feel free to re-open the issue if you have any additional inputs or possible solutions are not clear for you.
