### ISSUE TITLE
Deploy a single function in the serverless.yaml spec?

### ISSUE THREAD

**Issue by eddiewang** [triggermesh/tm#192]
Hi there,

triggermesh is pretty magical now that I've got it working! kudos to the team.
wanted to ask if there was a way to deploy only a single function in a serverless.yaml config. i've grouped a set of serverless handlers into a single repo. 

whenever i run `tm deploy -f bag-of-functions`, every single function is built and deployed via kaniko. many times, the code i've edited only touches a specific handler, and i would love to be able to specify which handler to manually trigger. would you know if that's a supported use case?

**Comment by tzununbekov** [comment]
hey @eddiewang, thanks for a feedback, we're glad that you like triggermesh

Try a following command, it should do what you need:
```
tm deploy -f bag-of-functions <function>
```
where `<function>` is a name of function from your serverless.yaml

**Comment by eddiewang** [comment]
worked perfectly :+1:  
thanks you. now to figure out how to do telemetry and monitoring on Knative + Istio :smile: fun times ahead...
