### ISSUE TITLE
PingSource supported?

### ISSUE THREAD

**Issue by eddiewang** [triggermesh/tm#194]
Hi there,

I think that the event.schedule tag may still be applying a CronJobSource, which has been deprecated in Knative since 0.13.
Do you know if PingSources are supported through the `serverless.yaml` def?

Thanks!

**Comment by tzununbekov** [comment]
Hey Eddie,

no, after CronJobSource was deprecated we've removed scheduling support from serverless.yaml manifests. If I remember correctly, PingSource spec is very similar to old CronJobSource so it may be easy to swap one with another. I'll take a look at this.
