### ISSUE TITLE
Add support for Configuration, Routes and Services

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#2]
from:

[https://github.com/knative/serving/tree/master/pkg/apis/serving/v1alpha1](https://github.com/knative/serving/tree/master/pkg/apis/serving/v1alpha1)

**Comment by sebgoa** [comment]
I deploy knative serving in the cluster, it now has the custom resource definitions:

```
$ kubectl get crd
NAME                                          AGE
builds.build.knative.dev                      9d
buildtemplates.build.knative.dev              9d
configurations.serving.knative.dev            1m
revisions.serving.knative.dev                 1m
routes.serving.knative.dev                    1m
services.serving.knative.dev                  1m
```

So you should be able to start _getting_ buildtemplates, configurations, revisions, routes and services

cc/ @tzununbekov

**Comment by sebgoa** [comment]
you should be able to _get_, _list_, _delete_ these resources

**Comment by tzununbekov** [comment]
Added delete, get and describe commands for described knative resources
