### ISSUE TITLE
v0.7.0 has no asset or changelog

### ISSUE THREAD

**Issue by antoineco** [triggermesh/tm#209]

**Comment by sameersbn** [comment]
the tm tests were broken at the time of release (fixed by https://github.com/triggermesh/tm/pull/205), as a result the release job was not completed. The tests have now been fixed and a new release will be pushed out once https://github.com/triggermesh/tm/pull/207 is merged.

**Comment by antoineco** [comment]
Shall we discard the release then? If there is no asset it's as if the release didn't happen, right?

**Comment by sameersbn** [comment]
i'll manually upload the assets and insert the changelogs instead

**Comment by sameersbn** [comment]
done https://github.com/triggermesh/tm/releases/tag/v0.7.0

**Comment by sameersbn** [comment]
just published v1.0.0 and everything works as expected.
