### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [triggermesh/tm#228]
It looks like the recent tags (v0.17.0, v0.18.0, v0.19.0) were not properly done as v0.16.0, which caused some confusion with the homebrew maintenance process, can you help clarifying it? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/105119

**Comment by tzununbekov** [comment]
@chenrui333 this project's active development is currently on hold, so the release issue was caused by the outdated tests and modules. [This](https://github.com/triggermesh/tm/pull/229) PR should fix the CI errors, we'll create the minor version release from it. Thanks for reporting!

**Comment by tzununbekov** [comment]
The latest release is online:
https://github.com/triggermesh/tm/releases/tag/v1.19.1

@chenrui333 do not hesitate to reopen this issue or create a new one if there is something else that we can help with.
