### ISSUE TITLE
The KUBECONFIG env isn't picked up like kubect does

### ISSUE THREAD

**Issue by solsson** [triggermesh/tm#27]
To reproduce:
 * Move your default `~/.kube/config` to `~/.kube/myconf`
 * `export KUBECONFIG=~/.kube/myconf`
 * Now `kubectl` can still connect to the cluster, for example `kubectl version`
 * Move `~/.tm/config.json` to a temporary location
 * Run for example `tm deploy service -n default imagetest-a --from-image solsson/knative-test-image:build0`

You get: `Can't read config file`

**Comment by tzununbekov** [comment]
Added `KUBECONFIG` env variable support
@solsson please verify

**Comment by solsson** [comment]
Works!
