### ISSUE TITLE
setup continuous delivery

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#3]
- [x] Setup CircleCI to run tests
- [x] Add CircleCI badge in README.md
- [x] On git tag push a release in the release page
- [ ] On release setup a brew formula (in upstream brew.sh repo) for quick install on OSX

**Comment by tzununbekov** [comment]
Requested Triggermesh organization auth for CircleCI in Github

**Comment by sebgoa** [comment]
let's skip the brew formula for now.
