### ISSUE TITLE
Switch to knative.registry as default registry

### ISSUE THREAD

**Issue by solsson** [triggermesh/tm#31]
The result of https://github.com/triggermesh/knative-local-registry/pull/3 but pending TBDs in https://github.com/triggermesh/knative-local-registry/pull/4, and also we must upgrade the registry in munuprod.

**Comment by sebgoa** [comment]
let's time this.

**Comment by tzununbekov** [comment]
Do we need to update `/etc/hosts` on cluster nodes to make knative.registry accessible?

**Comment by solsson** [comment]
We tested Ingress now in the workshop, with poor results. Lots of `413 Request Entity Too Large`. Docker push is apparently a quite demanding HTTP client.

**Comment by tzununbekov** [comment]
> We tested Ingress now in the workshop, with poor results. Lots of `413 Request Entity Too Large`. Docker push is apparently a quite demanding HTTP client.

@solsson I think it's registry proxy limitation. Docker documentation recommends set following parameter to 0: 
```
 # disable any limits to avoid HTTP 413 for large image uploads
 client_max_body_size 0;
```

https://docs.docker.com/registry/recipes/nginx/

**Comment by tzununbekov** [comment]
```
Get http://knative.registry.svc.cluster.local/v2/: dial tcp: lookup knative.registry.svc.cluster.local on 10.31.240.10:53: no such host
```
having this error during service deployment (image push step) in munuprod. @solsson, is there anything else besides `hosts` file should be updated in knative cluster to make registry accessible?

**Comment by tzununbekov** [comment]
ok, there was no `knative.registry` service created in munuprod cluster. Everything started to work after I created it manually

**Comment by solsson** [comment]
There's some activity at last in https://github.com/knative/serving/issues/1996 so maybe we'll be able to settle for such an internal hostname in the end.
