### ISSUE TITLE
check how to delete functions

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#38]
two cases:

* `tm remove` which removes all functions defined
* `tm deploy` where the `serverless.yml` has been updated, will it remove the missing functions.

**Comment by sebgoa** [comment]
Check the behavior of the serverless framework

**Comment by tzununbekov** [comment]
`tm remove -f <yaml>` removes all functions defined in this and all included yamls
`tm deploy -f <yaml>` doesn't handle functions that were removed from definition - will work on that now
