### ISSUE TITLE
Support single function deletion or deployment

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#41]
While we can deploy the whole set of functions defined in `serverless.yml` we should be able to deploy and remove a single function referenced by its name in the config file.

`tm remove foo`
`tm deploy foo`

**Comment by tzununbekov** [comment]
Done. `tm deploy` now accepts array of functions names, for example: 
```
tm deploy hello py -f https://github.com/tzununbekov/serverless
tm delete py
tm delete hello
```
