### ISSUE TITLE
Add support for Channel CRUD

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#42]
we shoudl be able to get/list/create/delete channels:

https://github.com/knative/eventing/blob/master/pkg/apis/eventing/v1alpha1/channel_types.go

```
tm create channel foobar
```

by default it should use the `in-memory-channel` clusterprovisioner

but we should be able to define a cluterprovisioner like:

```
tm create channel --provisioner foo foobar
```

**Comment by tzununbekov** [comment]
@sebgoa don't you mind if I use `tm deploy channel` command format to stick to our current CLI structure?

**Comment by tzununbekov** [comment]
```
tm get channels
tm deploy channel foo [--provisioner foobar]
tm describe channel foo
tm delete channel foo
```

**Comment by sebgoa** [comment]
Yah that's fine.

Even though we should use `tm create` instead of `tm deploy`
