### ISSUE TITLE
`--wait` takes a long time to return status 

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#51]
and if knative scales to zero before `--wait` has returned then the `tm deploy` returns an error.

Especially true in a CI gitlab deployment.

TBD

**Comment by tzununbekov** [comment]
`--wait` for scaled to zero service is fixed

Deployment time with `--wait` flag directly depends on service statuses returned from k8s. I was working on improvement by adding concurrency described in #44, but it's still in branch. After I finish those changes, `serverless.yaml` deployment process will last as long as it takes to deploy only one function

**Comment by sebgoa** [comment]
what happens if you don't `--wait` ?

**Comment by tzununbekov** [comment]
by default CLI starts service creation and passes next while `--wait` flag makes CLI wait for service components initialization, domain name availability and service `ready` status in general
