### ISSUE TITLE
Use knative service `release` and `manual` modes  

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/tm#53]

**Comment by tzununbekov** [comment]
Played a bit with `manual` service mode, figured out how it works and what it will take to reconfigure whole CLI to this configuration and I'm not sure if we need it now. The only advantage that I see we'll get from `manual` service type is ability to manage traffic routes but time required for implementation may negate that advantage. Not sure what to do here next.

**Comment by sebgoa** [comment]
these are deprecated in 0.7 , so I am closing this issue
