### ISSUE TITLE
fix CI so that we trigger on release tags with the `v` prefix

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#54]
it is better practice for release names

**Comment by tzununbekov** [comment]
Reconfigured CircleCI to use `v` prefix
@sebgoa please note, that to release new version, tag value also should be updated in code itself:
https://github.com/triggermesh/tm/blob/master/cmd/tm.go#L49

**Comment by tzununbekov** [comment]
https://github.com/triggermesh/tm/releases/tag/v0.0.7
