### ISSUE TITLE
accept `.yml` suffix 

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#55]
right now it only takes `serverless.yaml`

**Comment by cab105** [comment]
That is the default configuration when the file flag is not specified. One can specify an alternate file by way of `tm deploy -f <filename/url/repo>`.

However I have submitted PR: https://github.com/triggermesh/tm/pull/56 which will add a secondary check against serverless.yml.

**Comment by tzununbekov** [comment]
Merged, looks good now
