### ISSUE TITLE
Add secret mounting in service creation

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#60]
We should be able to specify a secret that can be mounted in the container that backs a service.

```
tm deploy service foo -f ... --secret refasecretink8s
```

think about where to mount it and how we could specify setting env vars with the secret as well.

**Comment by tzununbekov** [comment]
@sebgoa do we need to mount secret or setting env variables from secret keys would be enough?
if we need both options (mount volume and set env), I would use different argument, something like `--secret-volume <secret ref>:<path inside container>` and `--secret-env <secret ref>`

**Comment by sebgoa** [comment]
env might work for now.

**Comment by tzununbekov** [comment]
`--env-secret` parameter accepts k8s secret names which will be populated into pod env  
```
tm deploy service foo -f gcr.io/google-samples/hello-app:1.0 --env-secret secret1,secret2,secret3
```
serverless.yaml now also supports `env-secrets` key

**Comment by sebgoa** [comment]
so if I have a secret call `foo` that contains `password=foobar`

I get an ENV `password` set to `foobar` ?

What is there are several k/v in the secret ?

**Comment by tzununbekov** [comment]
correct. Each k/v pair of specified secret going to be k/v pair in pod env
