### ISSUE TITLE
Error "Can't get YAML file" for missing nouns

### ISSUE THREAD

**Issue by solsson** [triggermesh/tm#62]
For example `tm delete my-node-test` (forgot to write `service`) produces the error "Can't get YAML file".

**Comment by tzununbekov** [comment]
since we have `tm deploy` command (without "service" noun) which expects to read `serverless.yaml` in current path, `Can't get YAML file` response is expected behavior

**Comment by solsson** [comment]
IMO we must improve the message to be more informative towards a user who doesn't know that. Can be considered cosmetic though.

**Comment by tzununbekov** [comment]
[Same](https://github.com/triggermesh/tm/issues/64#issuecomment-453111551) here

**Comment by tzununbekov** [comment]
Will be tracked here: https://github.com/triggermesh/tm/issues/65
