### ISSUE TITLE
figure out how to use `--from-file`

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#7]
the knative build object currently only has google cloud storage and github sources: https://github.com/knative/build/blob/master/pkg/apis/build/v1alpha1/build_types.go#L102

how could we support using a local file like in kubeless with `--from-file`

**Comment by sebgoa** [comment]
we can definitely implement `--from-url` which would point to a file available over http, even a gist.

**Comment by tzununbekov** [comment]
I've made `--from-file` work this way:
1) local dockerfile being pushed to kubernetes as configmap
2) mount configmap as volume to kaniko
3) pass custom dockerfile path to kaniko buildtemple to make it build our image

It may be not the best solution but it works and we can change it to something better anytime
