### ISSUE TITLE
set the traffic percentage of a route

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tm#8]
with:

```
tm set route <route_name> --traffic=50
```

A route object can point traffic to different revisions (or configs..need to check), we should be able to use the CLI to quickly set the percentage of the traffic going to one revision.

**Comment by tzununbekov** [comment]
> A route object can point traffic to different revisions (or configs..need to check)

Route object can point to both revision and configuration, but not in the same target:
```
func (tt *TrafficTarget) Validate() *FieldError {
	switch {
	case tt.RevisionName != "" && tt.ConfigurationName != "":
		return &FieldError{
			Message: "Expected exactly one, got both",
			Paths:   []string{"revisionName", "configurationName"},
		}
...
```
